### ISSUE TITLE
Feature request: links

### ISSUE THREAD

**Issue by wz2b** [tulip/node-red-tulip-api#6]
The node red tulip library doesn't seem to have a way to deal with links.  Is this a planned feature?

**Comment by kcamenzind** [comment]
Yes, this is a planned feature. The new API endpoints need to be added manually, but doing so is on our radar. Thanks for bringing up.

**Comment by wz2b** [comment]
I'm working on a submission for this too, P.R. #8 but it's not ready yet.  Should I stop working on it because you have an official one coming?  Unlike #6, it's not difficult to create a workaround for this one; the main pain point is having to deal with authentication.  But if you're working on links support then I will stop, we don't need to duplicate efforts.

**Comment by kcamenzind** [comment]
Yep, we’ll put up an official one. It’s in the works.

**Comment by wz2b** [comment]
OK.  I'm going to see if I can figure out how to cancel that P.R. then :)

**Comment by kcamenzind** [comment]
Closing, fixed with https://github.com/tulip/node-red-tulip-api/pull/9
